### ISSUE TITLE
容易出现php内存溢出：使用中文转拼音时，中文越长越容易复现这个问题

### ISSUE THREAD

**Issue by gtcfla** [Yurunsoft/ChineseUtil#13]
$content = 'PHP的类名，函数，方法名是不区分大小写的，也就是说无论你怎么定义函数名，实际上在引擎层面查找的时候都是会统一转换成小写形式来做的。 也就是说strtolower的应用是非常普遍的';
 // 设为性能模式
  Chinese::setMode('SQLite');
  $res = Chinese::toPinyin($content, Pinyin::CONVERT_MODE_PINYIN, '');
  return $res['pinyin'][0] ?? '';

![image](https://user-images.githubusercontent.com/12646335/115983583-a718c400-a5d4-11eb-8b3e-19f43f430da0.png)
![image](https://user-images.githubusercontent.com/12646335/115983582-a718c400-a5d4-11eb-9338-4b7ee2393cb2.png)

**Comment by Yurunsoft** [comment]
是这样的，这个组件会把所有组合可能性都给计算出来，并不是那种给出一个准确结果的功能。所以不太适合大段文字的转换。

**Comment by gtcfla** [comment]
谢谢解答。因为我看到最终结果也是用了第一个转换拼音的结果，所以这个把所有可能性算出来的组合是否意义不大？因为只是想用来转换拼音做同音字匹配，其他的可能性用不到。

**Comment by Yurunsoft** [comment]
建议用这个：<https://github.com/overtrue/pinyin>
