### ISSUE TITLE
拼音分词在复杂字符串中有问题

### ISSUE THREAD

**Issue by Huxiuqi** [Yurunsoft/ChineseUtil#4]
$string = 'xixijinpingsb';
        $resp = Chinese::splitPinyin($string);

结果是
array(1) {
[0]=>
string(25) "x i x i j i n p i n g s b"
}

**Comment by Yurunsoft** [comment]
已在<https://github.com/Yurunsoft/ChineseUtil/commit/6a0ff9a9143988bc3a4b855bc9c000e04bb39cbd>中修复
