### ISSUE TITLE
这里编译好的 so 文件不能直接用吗

### ISSUE THREAD

**Issue by anhao** [Yurunsoft/ChineseUtil#6]
提示 : 
`
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'libchinese_util-swoole4.5.so' in Unknown on line 0
`

已安装环境: php7.4 swoole4.5

**Comment by anhao** [comment]
我自己编译了一份 so , 也是报这个错误
`
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'libchinese_util.so' in Unknown on line 0
`

**Comment by Yurunsoft** [comment]
一般来讲可以直接用的，这个不是扩展，不需要像扩展一样去启用

**Comment by Yurunsoft** [comment]
补充下了，自己编译时候的设置方法说明
<https://github.com/Yurunsoft/ChineseUtil/commit/9b3440c4f958a173613d326fd9de2a2bc5c65800>
