### ISSUE TITLE
Money::toChinese当金额为0时，返回空字符串

### ISSUE THREAD

**Issue by skys215** [Yurunsoft/ChineseUtil#8]
当参数为falsy时，会返回空字符串。
0，0.0，'0'均返回空字符串。
只有为'0.0'时返回零。

![image](https://user-images.githubusercontent.com/4977935/103342852-84165180-4ac5-11eb-8aad-33bb4d81e35d.png)

**Comment by Yurunsoft** [comment]
已经修复，建议先把版本切到dev-master，尝试一下是否解决了问题
