### ISSUE TITLE
toChinese(),当金额以.0结尾时，返回xxx圆零

### ISSUE THREAD

**Issue by skys215** [Yurunsoft/ChineseUtil#9]
如图所示

![image](https://user-images.githubusercontent.com/4977935/103343744-bf198480-4ac7-11eb-979d-ecc5ca9daf1e.png)

应该抹去零，或显示零角（毕竟传的是`.0`)

**Comment by Yurunsoft** [comment]
已经修复，建议先把版本切到dev-master，尝试一下是否解决了问题
